/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/suits.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List suits */
        get: operations["listSuits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places */
        get: operations["listPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List athletes */
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual_competitions.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List online competitions */
        get: operations["listOnlineCompetitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Suit: {
            id: number;
            name: string;
            make?: string | null;
            makeCode?: string | null;
            /** @enum {string} */
            category: "wingsuit" | "tracksuit" | "slick";
        };
        Place: {
            id: number;
            name: string;
            /** @enum {string} */
            kind: "skydive" | "base";
            latitude: number;
            longitude: number;
            country: {
                name?: string | null;
                code?: string | null;
            };
        };
        Profile: {
            id: number;
            name: string;
            countryId?: number | null;
        };
        OnlineCompetition: {
            id: number;
            name: string;
            discipline: string;
            range_from?: number | null;
            range_to?: number | null;
            group?: {
                id?: number;
                name?: string;
            } | null;
        };
        PageMeta: {
            currentPage: number;
            totalPages: number;
            totalCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSuits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All suits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suit"][];
                };
            };
        };
    };
    listPlaces: {
        parameters: {
            query?: {
                query?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of places */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        places: components["schemas"]["Place"][];
                        meta: components["schemas"]["PageMeta"];
                    };
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: {
                query?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of athletes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profiles: components["schemas"]["Profile"][];
                        meta: components["schemas"]["PageMeta"];
                    };
                };
            };
        };
    };
    listOnlineCompetitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Online competitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        online_competitions?: components["schemas"]["OnlineCompetition"][];
                    };
                };
            };
        };
    };
}
